version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql1/data11/
  web:
    build: .
    command: python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000
    container_name: django
    volumes:
      - .:/project11
    ports:
      - "8080:8000"
    depends_on:
      - db

volumes:
  postgres_data: